"""add_genre_and_age_rating_to_events

Revision ID: 230134c4c09d
Revises: 5b2d86a98236
Create Date: 2026-08-10 01:14:52.482643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import src.db.base


# revision identifiers, used by Alembic.
revision: str = '230134c4c09d'
down_revision: Union[str, None] = '5b2d86a98236'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('genre', sa.String(length=255), nullable=True))
    op.add_column('events', sa.Column('age_rating', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'age_rating')
    op.drop_column('events', 'genre')
    # ### end Alembic commands ###
