"""Initial schema

Revision ID: 5b2d86a98236
Revises: 
Create Date: 2026-08-08 14:49:23.442039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import src.db.base


# revision identifiers, used by Alembic.
revision: str = '5b2d86a98236'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processed_webhook_events',
    sa.Column('stripe_event_id', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('processed_at', src.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', src.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', src.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', src.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_processed_webhook_events'))
    )
    op.create_index(op.f('ix_processed_webhook_events_stripe_event_id'), 'processed_webhook_events', ['stripe_event_id'], unique=True)
    op.create_table('users',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_digest', sa.String(length=512), nullable=False),
    sa.Column('role', sa.Enum('ORGANIZER', 'CLIENT', 'GATEKEEPER', name='user_role', native_enum=False), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', src.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', src.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', src.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('events',
    sa.Column('organizer_id', sa.UUID(), nullable=False),
    sa.Column('external_tmdb_id', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('poster_url', sa.String(length=512), nullable=True),
    sa.Column('event_date', src.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('venue_name', sa.String(length=255), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('type', sa.Enum('SEATED', 'PISTA', name='event_type', native_enum=False), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', src.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', src.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', src.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organizer_id'], ['users.id'], name=op.f('fk_events_organizer_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_events'))
    )
    op.create_index(op.f('ix_events_organizer_id'), 'events', ['organizer_id'], unique=False)
    op.create_table('seats',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('seat_number', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('AVAILABLE', 'PENDING', 'RESERVED', name='seat_status', native_enum=False), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', src.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', src.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', src.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_seats_event_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_seats_user_id'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_seats')),
    sa.UniqueConstraint('event_id', 'seat_number', name='uq_seats_event_id_seat_number')
    )
    op.create_index(op.f('ix_seats_event_id'), 'seats', ['event_id'], unique=False)
    op.create_index(op.f('ix_seats_user_id'), 'seats', ['user_id'], unique=False)
    op.create_table('tickets',
    sa.Column('reservation_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('seat_number', sa.String(length=20), nullable=False),
    sa.Column('qr_code_token', sa.String(length=2048), nullable=False),
    sa.Column('share_link_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('VALID', 'USED', 'CANCELLED', name='ticket_status', native_enum=False), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', src.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', src.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', src.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], name=op.f('fk_tickets_client_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_tickets_event_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reservation_id'], ['seats.id'], name=op.f('fk_tickets_reservation_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tickets')),
    sa.UniqueConstraint('share_link_hash', name=op.f('uq_tickets_share_link_hash'))
    )
    op.create_index(op.f('ix_tickets_client_id'), 'tickets', ['client_id'], unique=False)
    op.create_index(op.f('ix_tickets_event_id'), 'tickets', ['event_id'], unique=False)
    op.create_index(op.f('ix_tickets_reservation_id'), 'tickets', ['reservation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tickets_reservation_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_event_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_client_id'), table_name='tickets')
    op.drop_table('tickets')
    op.drop_index(op.f('ix_seats_user_id'), table_name='seats')
    op.drop_index(op.f('ix_seats_event_id'), table_name='seats')
    op.drop_table('seats')
    op.drop_index(op.f('ix_events_organizer_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_processed_webhook_events_stripe_event_id'), table_name='processed_webhook_events')
    op.drop_table('processed_webhook_events')
    # ### end Alembic commands ###
