"""add payment_intent_id to tickets

Revision ID: 775f18f30bad
Revises: d60df282f737
Create Date: 2026-08-12 11:53:18.922904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import src.db.base


# revision identifiers, used by Alembic.
revision: str = '775f18f30bad'
down_revision: Union[str, None] = 'd60df282f737'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('payment_intent_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_tickets_payment_intent_id'), 'tickets', ['payment_intent_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tickets_payment_intent_id'), table_name='tickets')
    op.drop_column('tickets', 'payment_intent_id')
    # ### end Alembic commands ###
