"""add_tmdb_cache_columns_to_event

Revision ID: b237bf059c08
Revises: f0687ecdc84d
Create Date: 2026-08-10 09:22:59.381531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import src.db.base
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b237bf059c08'
down_revision: Union[str, None] = 'f0687ecdc84d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('release_date', sa.String(length=50), nullable=True))
    op.add_column('events', sa.Column('vote_average', sa.Numeric(precision=3, scale=1), nullable=True))
    op.add_column('events', sa.Column('cast', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('events', 'age_rating',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'age_rating',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.drop_column('events', 'cast')
    op.drop_column('events', 'vote_average')
    op.drop_column('events', 'release_date')
    # ### end Alembic commands ###
