"""add_index_to_genre_column

Revision ID: d60df282f737
Revises: b237bf059c08
Create Date: 2026-08-11 11:25:35.459033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import src.db.base


# revision identifiers, used by Alembic.
revision: str = 'd60df282f737'
down_revision: Union[str, None] = 'b237bf059c08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_events_genre'), 'events', ['genre'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_events_genre'), table_name='events')
    # ### end Alembic commands ###
